### ISSUE TITLE
PostgresSQL 15 support

### ISSUE THREAD

**Issue by simensol** [Opus10/django-pgtrigger#123]
When bumping PostgresSQL to `15.3`, I get the following exception when executing `python manage.py migrate`:

```bash
python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, manager, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying manager.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying manager.0002_initial_data... OK
  Applying sessions.0001_initial... OK
Traceback (most recent call last):
  File "/workspaces/backend/manage.py", line 21, in <module>
    main()
  File "/workspaces/backend/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/workspaces/backend/.venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/workspaces/backend/.venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/workspaces/backend/.venv/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/workspaces/backend/.venv/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/backend/.venv/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/backend/.venv/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 383, in handle
    emit_post_migrate_signal(
  File "/workspaces/backend/.venv/lib/python3.11/site-packages/django/core/management/sql.py", line 52, in emit_post_migrate_signal
    models.signals.post_migrate.send(
  File "/workspaces/backend/.venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/workspaces/backend/.venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/backend/.venv/lib/python3.11/site-packages/pgtrigger/apps.py", line 92, in install_on_migrate
    installation.install(database=using)
  File "/workspaces/backend/.venv/lib/python3.11/site-packages/pgtrigger/installation.py", line 36, in install
    prune(database=database)
  File "/workspaces/backend/.venv/lib/python3.11/site-packages/pgtrigger/installation.py", line 89, in prune
    for trigger in prunable(database=database):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/backend/.venv/lib/python3.11/site-packages/pgtrigger/installation.py", line 55, in prunable
    pg_maj_version = int(str(cursor.connection.server_version)[:-4])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Connection' object has no attribute 'server_version'
```

Any plans for bumping PostgresSQL to 15?

EDIT: When downgrading Python from 3.11 to 3.10.11, executing `python manage.py migrate` seems to work. Thus, the exception above is probably related to https://github.com/Opus10/django-pgtrigger/issues/122. However, since the documentation [states](https://github.com/Opus10/django-pgtrigger#compatibility) that only `Postgres 10 - 14` is supported, I keep this open.

**Comment by wesleykendall** [comment]
Is it possible this is psycopg3 and Django 4.2 related? I originally encountered this error whenever I tested against psycopg3

Regardless, it should be fixed in v4.7, which tests against pg15, psycopg3, dj4.2, and python3.11
